spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authority?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080

# 自定义的jwt配置
jwt:
  # 过期时间：10分钟
  expire: 600000
  # 密钥
  secret: 6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52